import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext(null)

const translations = {
  tr: {
    welcome: 'Hoş geldiniz',
    joinKriptotek: "Kriptotek'e katıl",
    joinDescription: 'Kripto varlıklarını takip et, portföyünü yönet.',
    forgotPassword: 'Şifremi Unuttum',
    resetPasswordDescription: 'Kayıtlı e-posta adresine şifre sıfırlama bağlantısı gönderelim.',
    email: 'E-posta',
    password: 'Şifre',
    passwordRepeat: 'Şifre Tekrar',
    fullName: 'Ad Soyad',
    fullNamePlaceholder: 'Adınız Soyadınız',
    emailPlaceholderRegister: 'ornek@mail.com',
    passwordPlaceholder: '********',
    confirmPasswordPlaceholder: 'Şifrenizi tekrar girin',
    rememberMe: 'Beni hatırla',
    login: 'Giriş Yap',
    loggingIn: 'Giriş yapılıyor...',
    createAccount: 'Hesap Oluştur',
    creatingAccount: 'Hesap oluşturuluyor...',
    or: 'veya',
    loginWithGoogle: 'Google ile Giriş Yap',
    registerWithGoogle: 'Google ile Kayıt Ol',
    noAccount: 'Hesabınız yok mu?',
    registerNow: 'Hemen kayıt olun',
    alreadyHaveAccount: 'Zaten hesabın var mı?',
    loginHere: 'Giriş yap',
    accountProblems: 'Hesabınla ilgili sorun mu yaşıyorsun?',
    contactSupport: 'Destek ile iletişime geç',
    emailAndPasswordRequired: 'E-posta ve şifre zorunludur.',
    validEmailError: 'Lütfen geçerli bir e-posta adresi girin.',
    passwordMinLength: 'Şifre en az 6 karakter olmalıdır.',
    loginErrorOccurred: 'Giriş yapılırken bir hata oluştu.',
    invalidCredential: 'E-posta veya şifre hatalı.',
    loginFailed: 'Giriş Başarısız',
    solutionSuggestions: 'Çözüm önerileri',
    checkEmailCorrect: 'E-posta adresinizi doğru girdiğinizden emin olun.',
    checkPasswordCase: 'Şifrenizde büyük/küçük harf kullanımını kontrol edin.',
    noAccountRegister: 'Hesabınız yoksa hemen kayıt olun:',
    resetPassword: 'Şifre sıfırla',
    emailRequired: 'E-posta zorunludur.',
    resetEmailInvalidMessage: 'Lütfen geçerli bir e-posta girin.',
    resetPasswordSuccess: 'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
    accountDeactivatedPasswordResetError: 'Hesabınız pasife alınmış. Lütfen destek ile iletişime geçin.',
    userNotFound: 'Bu e-posta adresine ait bir kullanıcı bulunamadı.',
    resetPasswordError: 'Şifre sıfırlama isteği başarısız oldu.',
    emailTooLongError: 'E-posta adresi çok uzun.',
    invalidEmailError: 'Bu e-posta adresi geçersiz veya izin verilmiyor.',
    sending: 'Gönderiliyor...',
    sendResetLink: 'Şifre Sıfırlama Bağlantısı Gönder',
    backToLogin: 'Giriş sayfasına dön',
    safe: 'Güvenli',
    fast: 'Hızlı',
    easy: 'Kolay',
    bull: 'Yükseliş',
    trade: 'Trade',
    profit: 'Kâr',
    // Header & Footer
    professionalCrypto: 'Profesyonel Kripto Takip',
    platformTitle: 'Gerçek Zamanlı Kripto Analiz Platformu',
    platformTagline: 'Profesyonel kripto analizi için ihtiyacınız olan her şey, tek platformda.',
    disclaimer: 'Kriptotek, eğitim ve bilgilendirme platformudur.',
    allRightsReserved: 'Tüm hakları saklıdır.',
    madeWith: 'tarafından yapıldı',
    // Navigation
    home: 'Ana Sayfa',
    marketOverview: 'Piyasa Özeti',
    supplyTracking: 'Arz Takibi',
    fedRateTracking: 'Fed Faiz Takibi',
    news: 'Haberler',
    trending: 'Trend',
    favorites: 'Favoriler',
    portfolio: 'Portföy',
    settings: 'Ayarlar',
    admin: 'Yönetim',
    premiumUser: 'Premium',
    // Header
    emailNotVerified: 'E-postanız doğrulanmamış. Lütfen gelen kutunuzu kontrol edin.',
    resendVerificationEmail: 'Tekrar Gönder',
    verificationEmailSentAgain: '✅ Doğrulama emaili tekrar gönderildi!',
    goToPremium: "Premium'a Geç",
    user: 'Kullanıcı',
    profileSettings: 'Profil Ayarları',
    logout: 'Çıkış Yap',
    // Forgot Password
    resetSummaryTitle: 'E-posta Gönderildi',
    requestSent: 'Şifre sıfırlama isteğiniz gönderildi.',
    emailSentLabel: 'E-posta gönderildi:',
    resetSummaryItemInbox: 'E-posta kutunuzu kontrol edin',
    resetSummaryItemSpam: 'Spam klasörünü de kontrol edin',
    resetSummaryItemWait: 'E-postanın gelmesi birkaç dakika sürebilir',
    emailNotReceivedIn5mins: '5 dakika içinde e-posta gelmezse spam klasörünü kontrol edin veya farklı bir e-posta deneyin.',
    createNewAccount: 'Yeni Hesap Oluştur',
    tryDifferentEmail: 'Farklı E-posta Dene',
    // Security
    captchaRequired: 'CAPTCHA cevabı gereklidir.',
    captchaIncorrect: 'CAPTCHA cevabı yanlış.',
    captchaIncorrectAttemptsLeft: 'Yanlış cevap. Kalan deneme: {attempts}',
    tooManyFailedAttempts: 'Çok fazla başarısız deneme. {seconds} saniye sonra tekrar deneyin.',
    loginBlockedForSecurity: 'Güvenlik nedeniyle {seconds} saniye boyunca bloklandınız.',
    securityVerification: 'Güvenlik Doğrulaması',
    verifyNotBot: 'Bot olmadığınızı doğrulamak için matematik sorusunu cevaplayın:',
    yourAnswer: 'Cevabınız',
    // Register
    allFieldsRequired: 'Tüm alanlar doldurulmalıdır',
    displayNameLengthError: 'İsim 2-50 karakter arasında olmalıdır',
    passwordLengthError: 'Şifre en az 8 karakter olmalıdır',
    passwordStrengthError: 'Şifre en az bir büyük harf, bir küçük harf ve bir rakam içermelidir',
    registerError: 'Kayıt sırasında bir hata oluştu',
    emailAlreadyInUse: 'Bu e-posta adresi zaten kullanılıyor',
    googleLoginError: 'Google ile giriş yapılırken bir hata oluştu',
    verificationEmailSent: 'Doğrulama Emaili Gönderildi!',
    verificationEmailSentTo: 'adresine bir doğrulama emaili gönderdik.',
    checkYourInboxAndSpam: 'Lütfen email kutunuzu kontrol edin ve doğrulama linkine tıklayın. Spam klasörünü de kontrol etmeyi unutmayın!',
    // Home Page
    cryptoList: 'Kripto Listesi',
    cryptoListDescription: 'Tüm kripto paraları keşfedin ve takip edin',
    topGainers: 'En Çok Yükselenler',
    topLosers: 'En Çok Düşenler',
    todayTopMovers: 'Bugünün en çok hareket edenleri',
    searchPlaceholder: 'Kripto ara...',
    marketCap: 'Piyasa Değeri',
    marketCapShort: 'Piyasa',
    volume24h: '24s Hacim',
    volume24hShort: 'Hacim',
    change24h: '24s Değişim',
    price: 'Fiyat',
    name: 'İsim',
    symbol: 'Sembol',
    crypto: 'Kripto',
    priceAndChange: 'Fiyat/24s',
    circulatingSupply: 'Arz',
    circulatingSupplyShort: 'Arz',
    supply: 'Arz',
    reset: 'Sıfırla',
    // Favorites
    favoritesTitle: 'Favoriler',
    favoritesDescription: 'Sık kullandığınız coinleri takip edin',
    noFavorites: 'Henüz favori yok',
    noFavoritesDesc: 'Favorilerinize coin eklemek için anasayfadaki yıldız ikonuna tıklayın',
    clearAllFavorites: 'Tümünü Temizle',
    clearAllFavoritesConfirmation: 'Tüm favorilerinizi silmek istediğinize emin misiniz?',
    addFavorite: 'Favorilere Ekle',
    removeFavorite: 'Favorilerden Çıkar',
    aiPrediction: 'AI Tahmin',
    goToHome: 'Ana Sayfaya Git',
    // Portfolio
    portfolioDescription: 'Pozisyonlarınızı takip edin ve kar/zarar hesaplayın',
    addPosition: 'Pozisyon Ekle',
    editPosition: 'Pozisyon Düzenle',
    deletePosition: 'Pozisyonu Sil',
    deletePositionConfirmation: 'Bu pozisyonu silmek istediğinizden emin misiniz?',
    noPositions: 'Henüz pozisyon yok',
    noPositionsDescription: 'İlk pozisyonunuzu ekleyerek başlayın',
    addFirstPosition: 'İlk Pozisyonu Ekle',
    coin: 'Coin',
    selectCoin: 'Coin Seçin',
    positionType: 'Pozisyon Tipi',
    long: 'Long',
    short: 'Short',
    amount: 'Miktar',
    entryPrice: 'Giriş Fiyatı',
    currentPrice: 'Mevcut Fiyat',
    notes: 'Notlar (Opsiyonel)',
    notesPlaceholder: 'Notlarınızı buraya yazın...',
    cancel: 'İptal',
    add: 'Ekle',
    update: 'Güncelle',
    delete: 'Sil',
    edit: 'Düzenle',
    totalPortfolioValue: 'Toplam Portföy Değeri',
    totalProfitLoss: 'Toplam Kar/Zarar',
    totalPositions: 'Toplam Pozisyon',
    currentValue: 'Güncel Değer',
    profitLoss: 'Kar/Zarar',
    profitLossPercent: 'Kar/Zarar %',
    isLeveraged: 'Kaldıraçlı İşlem?',
    yes: 'Evet',
    no: 'Hayır',
    leverage: 'Kaldıraç',
    longDescription: 'Yükselişten kazan',
    shortDescription: 'Düşüşten kazan',
    investmentAmount: 'Yatırım Miktarı',
    coinAmount: 'Alınacak Coin Miktarı',
    stopLoss: 'Stop Loss',
    takeProfit: 'Hedef Fiyat (Take Profit)',
    takeProfitShort: 'Hedef',
    stopLossShort: 'Stop',
    optional: 'Opsiyonel',
    stopLossPlaceholder: 'Stop loss fiyatı (opsiyonel)',
    takeProfitPlaceholder: 'Hedef fiyat (opsiyonel)',
    stopLossResult: 'Stop Loss Sonucu',
    takeProfitResult: 'Hedef Fiyat Sonucu',
    stopLossTriggered: 'Stop Loss Tetiklendi!',
    takeProfitTriggered: 'Hedef Fiyat Ulaşıldı!',
    portfolioLoading: 'Portföy yükleniyor...',
    searchCoin: 'Coin ara...',
    noCoinFound: 'Coin bulunamadı',
    spotTradeInfo: 'Spot işlem: Yükselişten kazanırsınız.',
    spot: 'Spot',
    portfolioLoadError: 'Portföy yüklenemedi',
    positionAddError: 'Pozisyon eklenemedi',
    positionUpdateError: 'Pozisyon güncellenemedi',
    positionDeleteError: 'Pozisyon silinemedi',
    // Trending
    trendingTitle: 'Trend Kripto Paralar',
    trendingDescription: 'AI destekli trend analizi ile en popüler coinleri keşfedin',
    trendScore: 'Trend Skoru',
    noTrendingCoins: 'Trend coin bulunamadı',
    searchCryptos: 'Kripto ara...',
    noResultsFor: '{searchTerm} için sonuç bulunamadı',
    updating: 'Güncelleniyor...',
    veryStrongTrend: 'Çok Güçlü Trend',
    strongTrend: 'Güçlü Trend',
    moderateTrend: 'Orta Trend',
    weakTrend: 'Zayıf Trend',
    veryWeakTrend: 'Çok Zayıf Trend',
    strongBullish: 'Güçlü Yükseliş',
    bullish: 'Yükseliş',
    strongBearish: 'Güçlü Düşüş',
    bearish: 'Düşüş',
    positionBadgeLong: 'Long',
    positionBadgeShort: 'Short',
    positionBadgeNeutral: 'Nötr',
    viewDetails: 'Detayları Görüntüle',
    predictionBasePrice: 'Tahmin Baz Fiyatı',
    estimatedPrice: 'Tahmini Fiyat',
    estimatedChange: 'Tahmini Değişim',
    direction: 'Yön',
    algorithmicPricePrediction: 'Algoritmik Fiyat Tahmini',
    totalTrendScore: 'Toplam Trend Skoru',
    totalTrendScoreDesc: 'Tüm faktörlerin birleşik değerlendirmesi',
    detailedAnalysisMetrics: 'Detaylı Analiz Metrikleri',
    liquidityScore: 'Likidite Skoru',
    priceMomentum: 'Fiyat Momentumu',
    marketPosition: 'Piyasa Pozisyonu',
    volumeTrend: 'Hacim Trendi',
    volatilityScore: 'Volatilite Skoru',
    volumeMarketCapRatio: 'Hacim / Piyasa Değeri Oranı',
    priceChange24h: '24 Saatlik Fiyat Değişimi',
    marketCapRankDesc: 'Piyasa Değeri Sıralaması',
    tradingVolumeActivity: 'İşlem Hacmi Aktivitesi',
    priceVolatility: 'Fiyat Volatilitesi',
    chartLoading: 'Grafik yükleniyor...',
    priceAndChangeMobile: 'Fiyat / 24s',
    trendScoreDescription: '📊 Bir coin\'in piyasadaki popülerliğini ve hareketliliğini ölçer.\n\n• Fiyat değişimi\n• İşlem hacmi\n• Likidite\n• Piyasa değeri\n• Volatilite\n\nSkor: 0-100\n🟢 70-100: Güçlü trend\n🟡 30-70: Orta trend\n🔴 0-30: Zayıf trend',
    positionDescription: '🤖 AI modelinin önerdiği işlem yönü:\n\n📈 Long Pozisyonu:\nFiyat yükseliş bekleniyor → Al\n\n📉 Short Pozisyonu:\nFiyat düşüş bekleniyor → Sat\n\n⚪ Nötr:\nBelirsizlik var\n\n⚠️ Yatırım tavsiyesi değildir.',
    marketCapMobile: 'P. Değeri',
    supplyMobile: 'Arz',
    volumeMobile: 'Hacim (24h)',
    noData: 'Veri yok',
    volumeMarketCapExplanation: 'Hacim ve Piyasa Değeri Açıklaması',
    thousand: 'Bin (K)',
    thousandExplanation: '1,000',
    million: 'Milyon (M)',
    millionExplanation: '1,000,000',
    billion: 'Milyar (B)',
    billionExplanation: '1,000,000,000',
    trillion: 'Trilyon (T)',
    trillionExplanation: '1,000,000,000,000',
    // Premium Route
    premiumRequired: 'Premium Üyelik Gerekli',
    premiumRequiredDesc: 'Bu özelliğe erişmek için Premium üyeliğe ihtiyacınız var',
    premiumFeaturePortfolio: 'Portföy Yönetimi',
    premiumFeaturePortfolioDesc: 'Long/Short pozisyon takibi, kar/zarar hesaplama ve fiyat uyarıları',
    premiumFeatureDominance: 'Dominance Analizi',
    premiumFeatureDominanceDesc: 'BTC ve ETH piyasa hakimiyeti grafikleri ve trend analizi',
    premiumFeatureTrend: 'Trend Analizi',
    premiumFeatureTrendDesc: 'Popüler kripto trendlerini ve momentum skorlarını takip et',
    premiumFeatureFavorites: 'Favoriler',
    premiumFeatureFavoritesDesc: 'Sık kullandığınız coinleri kaydedin ve hızlı erişin',
    premiumFeatureFedRate: 'Faiz Takibi',
    premiumFeatureFedRateDesc: 'FED faiz oranlarını takip edin ve piyasa etkilerini analiz edin',
    premiumFeatureSupply: 'Arz Takibi',
    premiumFeatureSupplyDesc: 'Coin arz değişimlerini 24 saat, 7 gün ve 30 günlük periyotlarda görüntüleyin',
    // Supply Tracking
    supplySearchPlaceholder: 'Coin ara...',
    supplySortLabel: 'Sırala',
    supplySortDefault: 'Varsayılan',
    supplySortName: 'İsim',
    supplySortChange24h: '24h Değişim',
    supplySortChange7d: '7d Değişim',
    supplySortChange1m: '1m Değişim',
    supplyChange24h: '24h Değişim',
    supplyChange7d: '7d Değişim',
    supplyChange30d: '30d Değişim',
    circulatingSupplyFull: 'Dolaşımdaki Arz',
    totalSupplyFull: 'Toplam Arz',
    maxSupplyFull: 'Maksimum Arz',
    noSupplyData: 'Henüz supply verisi yok',
    premiumFeatureMarket: 'Market Overview',
    premiumFeatureMarketDesc: 'Piyasa genel görünümü, dominance grafikleri ve Fear & Greed Index',
    premiumFeatureCharts: 'Gelişmiş Grafikler',
    premiumFeatureChartsDesc: 'Detaylı OHLC mum grafikleri ve teknik analiz araçları',
    buyPremium: 'Premium Satın Al',
    backToHome: 'Ana Sayfaya Dön',
    premiumContactInfo: 'Premium üyelik hakkında bilgi almak için:',
    telegram: 'Telegram',
    // NotFound Page
    notFoundBadge: 'Kaybolmuş rota',
    notFoundTitle: 'Yanlış koordinata sıçradın',
    notFoundDescription: 'Radarlar bu noktada bir portal bulamadı. Yıldız haritamız seni tekrar ana üsse yönlendirmek için hazırlanıyor. Bu sırada kozmik pelerinini topla ve güvenli rotaya geri dön.',
    notFoundStatus1: 'Navigasyon yeniden hesaplanıyor',
    notFoundStatus2: 'Warp motoru hazır beklemede',
    notFoundStatus3: 'Yedek rota çiziliyor',
    notFoundBackHome: 'Ana üsse dön',
    notFoundSupport: 'Devam eden sorunlar için',
    notFoundSupportTeam: 'destek ekibimizle',
    notFoundSupportContact: 'bağlantı kurabilirsin.',
    // Dominance Page
    dominanceTitle: 'Piyasa Hakimiyeti',
    dominanceDescription: 'Bitcoin ve Ethereum piyasa hakimiyeti analizi',
    dominanceTable: 'Hakimiyet Tablosu',
    topDominance: 'Hakimiyeti',
    totalBtcVolume: 'Toplam BTC Hacmi',
    // Admin Management
    adminManagement: 'Kullanıcı Yönetimi',
    adminManagementDescription: 'Kullanıcıları görüntüle, düzenle ve yönet',
    unauthorizedAccess: 'Yetkisiz Erişim',
    unauthorizedAccessDesc: 'Bu sayfaya erişmek için admin yetkisine ihtiyacınız var.',
    searchUser: 'Kullanıcı ara...',
    all: 'Tümü',
    regular: 'Normal',
    inactive: 'Pasif',
    totalUsers: 'Toplam Kullanıcı',
    premiumUsers: 'Premium Kullanıcılar',
    regularUsers: 'Normal Kullanıcılar',
    refresh: 'Yenile',
    makePremium: 'Premium Yap',
    removePremium: 'Premium Kaldır',
    makeAdmin: 'Admin Yap',
    removeAdmin: 'Admin Kaldır',
    activate: 'Aktif Et',
    deactivate: 'Pasif Et',
    userNotFoundDescription: 'Arama kriterlerinize uygun kullanıcı bulunamadı.',
    unknown: 'Bilinmiyor',
    userId: 'Kullanıcı ID',
    marketCapPercentage: 'Piyasa Değeri Yüzdesi',
    volume24hDominance: '24s Hacim Hakimiyeti',
    change24hDominance: '24s Değişim',
    cryptocurrency: 'Kripto Para',
    marketShareDistributionOverlay: 'Piyasa Payı Dağılımı',
    last7Days: 'Son 7 Gün',
    volumeAnalysis: 'Hacim Analizi',
    dataLoading: 'Veri yükleniyor...',
    date: 'Tarih',
    dominance: 'Hakimiyet',
    extremeFear: 'Aşırı Korku',
    fear: 'Korku',
    neutral: 'Nötr',
    greed: 'Açgözlülük',
    extremeGreed: 'Aşırı Açgözlülük',
    dominanceApiErrorTitle: 'Veri Yüklenemedi',
    dominanceApiErrorDesc: 'Dominance verileri yüklenirken bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
    others: 'Diğerleri',
    // News
    cryptoNews: 'Kripto Haberler',
    justNow: 'az önce',
    minutesAgo: 'dakika önce',
    hoursAgo: 'saat önce',
    searchNews: 'Haberlerde ara...',
    errorLoadingNews: 'Haberler yüklenirken bir hata oluştu:',
    noNewsFound: 'Aradığınız kriterlere uygun haber bulunamadı',
    noNews: 'Henüz haber yok',
    readMore: 'Devamı',
    important: 'Önemli',
    positive: 'Pozitif',
    negative: 'Negatif',
    highPriorityNews: 'Yüksek Öncelikli Haber',
    criticalImportance: 'Kritik öneme sahip haberler',
    recordOrImportant: 'Rekor veya önemli gelişmeler',
    positiveNews: 'Pozitif Haber',
    negativeNews: 'Negatif Haber',
    neutralNews: 'Nötr Haber',
    positiveNewsDesc: 'Piyasa için olumlu haberler',
    negativeNewsDesc: 'Piyasa için olumsuz haberler',
    neutralNewsDesc: 'Bilgi amaçlı haberler',
    positiveForMarket: 'Piyasa için olumlu',
    needsCaution: 'Dikkat gerektirir',
    informationalOnly: 'Bilgilendirme',
    marketImpactAnalysis: 'Piyasa Etki Analizi',
    negativeForMarket: 'Piyasa için olumsuz',
    aiAnalysisNeutral: 'Bilgi amaçlı',
    newsCategory: 'Haber Kategorisi',
    category: 'Kategori',
    categoryBitcoin: 'Bitcoin',
    categoryEthereum: 'Ethereum',
    categoryDefi: 'DeFi',
    categoryNft: 'NFT',
    categoryRegulation: 'Regülasyon',
    categoryExchange: 'Borsa',
    categoryMarket: 'Piyasa',
    categoryAltcoin: 'Altcoin',
    categoryBitcoinShort: 'Bitcoin haberleri',
    categoryEthereumShort: 'Ethereum haberleri',
    categoryDefiShort: 'DeFi haberleri',
    categoryNftShort: 'NFT haberleri',
    categoryRegulationShort: 'Regülasyon haberleri',
    categoryExchangeShort: 'Borsa haberleri',
    categoryMarketShort: 'Piyasa haberleri',
    categoryAltcoinShort: 'Altcoin haberleri',
    defi: 'DeFi',
    nft: 'NFT',
    regulation: 'Regülasyon',
    exchange: 'Borsa',
    market: 'Piyasa',
    altcoin: 'Altcoin',
    // Settings Page
    settingsTitle: 'Ayarlar',
    settingsDescription: 'Profilinizi, görünüm ayarlarınızı ve güvenliğinizi yönetin.',
    profileInfo: 'Profil Bilgileri',
    display: 'Görünüm',
    theme: 'Tema',
    themeDescription: 'Arayüz temasını seçin',
    light: 'Açık',
    dark: 'Koyu',
    language: 'Dil',
    languageLabel: 'Dil',
    currency: 'Para Birimi',
    currencyLabel: 'Para Birimi',
    usd: 'USD',
    eur: 'EUR',
    try: 'TRY',
    currentRates: 'TRY Bazında Kurlar',
    passwordChange: 'Şifre Değiştirme',
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre',
    confirmNewPassword: 'Yeni Şifre Tekrarı',
    enterCurrentPassword: 'Mevcut şifrenizi girin',
    enterNewPassword: 'Yeni şifrenizi girin',
    changePassword: 'Şifreyi Değiştir',
    setPassword: 'Şifre Belirle',
    changingPassword: 'Şifre değiştiriliyor...',
    passwordStrength: 'Şifre Gücü',
    minLength: '8+ Karakter',
    hasUppercase: 'En az bir büyük harf',
    hasLowercase: 'En az bir küçük harf',
    hasNumber: 'En az bir sayı',
    hasSpecialChar: 'En az bir özel karakter',
    weak: 'Zayıf',
    medium: 'Orta',
    strong: 'Güçlü',
    veryStrong: 'Çok Güçlü',
    passwordTooWeak: 'Şifre çok zayıf',
    currentPasswordRequired: 'Mevcut şifre gerekli',
    newPasswordRequired: 'Yeni şifre gerekli',
    wrongCurrentPassword: 'Mevcut şifre hatalı',
    passwordChanged: 'Şifre başarıyla değiştirildi',
    newPasswordMustBeDifferent: 'Yeni şifre eski şifre ile aynı olamaz',
    accountDeletion: 'Hesap Silme',
    deleteAccountPermanently: 'Hesabınızı ve tüm verilerinizi kalıcı olarak silin.',
    deleteMyAccount: 'Hesabımı Sil',
    confirmAccountDeletion: 'Hesabı Silmeyi Onayla',
    accountDeletionWarning: 'Bu işlem geri alınamaz. Hesabınız ve tüm verileriniz kalıcı olarak silinecektir.',
    dataToBeDeleted: 'Silinecek Veriler:',
    personalInformation: 'Kişisel Bilgiler',
    favoriteCryptoList: 'Favori Kripto Listeniz',
    accountSettings: 'Hesap Ayarlarınız',
    allCacheData: 'Tüm Önbellek Verileri',
    accountDeletionPasswordNote: 'Hesabınızı silmek için mevcut şifrenizi girmeniz gerekmektedir.',
    yesDeleteAccount: 'Evet, Hesabımı Sil',
    accountDeletedSuccessfully: 'Hesap başarıyla silindi',
    accountDeletionError: 'Hesap silme hatası',
    deleting: 'Siliniyor',
    confirm: 'Onayla',
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    saveSuccess: 'Başarıyla kaydedildi',
    saveError: 'Kaydetme hatası',
    loginRequiredToSave: 'Kaydetmek için giriş gerekli',
    loginRequiredToReset: 'Sıfırlamak için giriş gerekli',
    resetSettings: 'Ayarları Sıfırla',
    settingsReset: 'Ayarlar sıfırlandı',
    unsavedChanges: 'Kaydedilmemiş değişiklikler var',
    updateProfile: 'Profili Güncelle',
    updatingProfile: 'Profil güncelleniyor...',
    profileUpdateSuccess: 'Profil başarıyla güncellendi',
    profileUpdateError: 'Profil güncelleme hatası',
    loading: 'Yükleniyor...',
    settingsSummary: 'Ayarlar Özeti',
    // MiniChart
    chartClickToView: 'Grafiği görmek için coin kartına tıklayın',
    chartDataLoading: 'Veri yükleniyor...',
    chartDataUnavailable: 'OHLC verisi mevcut değil',
    chartDataLoadError: 'OHLC verisi yüklenemedi',
    // Dominance
    marketDominanceBreakdown: 'Market dominance breakdown',
    topCryptocurrenciesByVolume: 'Top cryptocurrencies by volume',
    // Layout
    loadingPage: 'Yükleniyor...',
    // Common
    notAvailable: 'Mevcut Değil',
    loadUsersError: 'Kullanıcılar yüklenemedi',
    togglePremiumError: 'Premium durumu değiştirilemedi',
    toggleActiveError: 'Kullanıcı durumu değiştirilemedi',
    toggleAdminError: 'Admin durumu değiştirilemedi',
    bitcoin: 'Bitcoin',
    ethereum: 'Ethereum',
    // Fed Rate
    fedRateDescription: 'FED faiz oranlarını takip edin ve piyasa etkilerini analiz edin',
    fedRateDecision: 'Fed Faiz Kararı',
    announced: 'Açıklanan',
    previous: 'Önceki',
    lastPublished: 'Son Yayınlanma',
    nextDecision: 'Sonraki Karar',
    fedRssLink: 'Fed RSS Bağlantısı',
    fomcCalendarLink: 'FOMC Takvimi',
    announcing: 'Açıklanıyor...',
    waitingForData: 'Veri bekleniyor...',
    week: 'Hafta',
    day: 'Gün',
    hour: 'Saat',
    minute: 'Dakika',
    second: 'Saniye',
    fredApiKeyMissing: 'FRED API anahtarı eksik',
    fedRateDataError: 'Fed Rate verisi yüklenemedi. Lütfen sayfayı yenileyin.'
  },
  en: {
    welcome: 'Welcome',
    joinKriptotek: 'Join Kriptotek',
    joinDescription: 'Track your crypto assets and manage your portfolio.',
    forgotPassword: 'Forgot Password',
    resetPasswordDescription: 'We will send a password reset link to your email.',
    email: 'Email',
    password: 'Password',
    passwordRepeat: 'Password Repeat',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Your full name',
    emailPlaceholderRegister: 'example@mail.com',
    passwordPlaceholder: '********',
    confirmPasswordPlaceholder: 'Re-enter your password',
    rememberMe: 'Remember me',
    login: 'Login',
    loggingIn: 'Logging in...',
    createAccount: 'Create Account',
    creatingAccount: 'Creating account...',
    or: 'or',
    loginWithGoogle: 'Login with Google',
    registerWithGoogle: 'Register with Google',
    noAccount: "Don't have an account?",
    registerNow: 'Register now',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    accountProblems: 'Having problems with your account?',
    contactSupport: 'Contact support',
    emailAndPasswordRequired: 'Email and password are required.',
    validEmailError: 'Please enter a valid email address.',
    passwordMinLength: 'Password must be at least 6 characters.',
    loginErrorOccurred: 'An error occurred while logging in.',
    invalidCredential: 'Invalid email or password.',
    loginFailed: 'Login Failed',
    solutionSuggestions: 'Solution suggestions',
    checkEmailCorrect: 'Make sure your email is correct.',
    checkPasswordCase: 'Check upper/lower case in your password.',
    noAccountRegister: 'If you do not have an account, register now:',
    resetPassword: 'Reset password',
    emailRequired: 'Email is required.',
    resetEmailInvalidMessage: 'Please enter a valid email.',
    resetPasswordSuccess: 'Password reset link has been sent to your email.',
    accountDeactivatedPasswordResetError: 'Your account is deactivated. Please contact support.',
    userNotFound: 'No user found for this email address.',
    resetPasswordError: 'Password reset request failed.',
    emailTooLongError: 'Email address is too long.',
    invalidEmailError: 'This email is invalid or not allowed.',
    sending: 'Sending...',
    sendResetLink: 'Send Password Reset Link',
    backToLogin: 'Back to login',
    safe: 'Safe',
    fast: 'Fast',
    easy: 'Easy',
    bull: 'Bull',
    trade: 'Trade',
    profit: 'Profit',
    // Header & Footer
    professionalCrypto: 'Professional Crypto Tracking',
    platformTitle: 'Kriptotek',
    platformTagline: 'Track your crypto assets professionally',
    disclaimer: '⚠️ Not investment advice. Cryptocurrency investments are risky.',
    allRightsReserved: 'All rights reserved.',
    madeWith: 'made with',
    // Navigation
    home: 'Home',
    marketOverview: 'Market Overview',
    supplyTracking: 'Supply Tracking',
    fedRateTracking: 'Fed Rate Tracking',
    news: 'News',
    trending: 'Trending',
    favorites: 'Favorites',
    portfolio: 'Portfolio',
    settings: 'Settings',
    admin: 'Admin',
    premiumUser: 'Premium',
    // Header
    emailNotVerified: 'Your email is not verified. Please check your inbox.',
    resendVerificationEmail: 'Resend',
    verificationEmailSentAgain: '✅ Verification email sent again!',
    goToPremium: 'Go Premium',
    user: 'User',
    profileSettings: 'Profile Settings',
    logout: 'Logout',
    // Forgot Password
    resetSummaryTitle: 'Email Sent',
    requestSent: 'Your password reset request has been sent.',
    emailSentLabel: 'Email sent to:',
    resetSummaryItemInbox: 'Check your inbox',
    resetSummaryItemSpam: 'Also check your spam folder',
    resetSummaryItemWait: 'Email may take a few minutes to arrive',
    emailNotReceivedIn5mins: 'If you don\'t receive an email within 5 minutes, check spam or try a different email.',
    createNewAccount: 'Create New Account',
    tryDifferentEmail: 'Try Different Email',
    // Security
    captchaRequired: 'CAPTCHA answer is required.',
    captchaIncorrect: 'CAPTCHA answer is incorrect.',
    captchaIncorrectAttemptsLeft: 'Wrong answer. Attempts left: {attempts}',
    tooManyFailedAttempts: 'Too many failed attempts. Try again in {seconds} seconds.',
    loginBlockedForSecurity: 'Blocked for {seconds} seconds for security reasons.',
    securityVerification: 'Security Verification',
    verifyNotBot: 'Answer the math question to verify you are not a bot:',
    yourAnswer: 'Your Answer',
    // Register
    allFieldsRequired: 'All fields are required',
    displayNameLengthError: 'Name must be between 2-50 characters',
    passwordLengthError: 'Password must be at least 8 characters',
    passwordStrengthError: 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
    passwordsNotMatch: 'Passwords do not match',
    registerError: 'An error occurred during registration',
    emailAlreadyInUse: 'This email address is already in use',
    googleLoginError: 'An error occurred while logging in with Google',
    verificationEmailSent: 'Verification Email Sent!',
    verificationEmailSentTo: 'We have sent a verification email to',
    checkYourInboxAndSpam: 'Please check your email inbox and click the verification link. Don\'t forget to check your spam folder!',
    // Home Page
    cryptoList: 'Crypto List',
    cryptoListDescription: 'Discover and track all cryptocurrencies',
    topGainers: 'Top Gainers',
    topLosers: 'Top Losers',
    todayTopMovers: 'Today\'s top movers',
    searchPlaceholder: 'Search crypto...',
    marketCap: 'Market Cap',
    marketCapShort: 'Market',
    volume24h: '24h Volume',
    volume24hShort: 'Volume',
    change24h: '24h Change',
    price: 'Price',
    name: 'Name',
    symbol: 'Symbol',
    crypto: 'Crypto',
    priceAndChange: 'Price/24h',
    circulatingSupply: 'Circulating Supply',
    circulatingSupplyShort: 'Supply',
    supply: 'Supply',
    reset: 'Reset',
    // Favorites
    favoritesTitle: 'Favorites',
    favoritesDescription: 'Track your frequently used coins',
    noFavorites: 'No favorites yet',
    noFavoritesDesc: 'Click the star icon on the home page to add coins to your favorites',
    clearAllFavorites: 'Clear All',
    clearAllFavoritesConfirmation: 'Are you sure you want to delete all your favorites?',
    addFavorite: 'Add to Favorites',
    removeFavorite: 'Remove from Favorites',
    aiPrediction: 'AI Prediction',
    goToHome: 'Go to Home',
    // Portfolio
    portfolioDescription: 'Track your positions and calculate profit/loss',
    addPosition: 'Add Position',
    editPosition: 'Edit Position',
    deletePosition: 'Delete Position',
    deletePositionConfirmation: 'Are you sure you want to delete this position?',
    noPositions: 'No positions yet',
    noPositionsDescription: 'Start by adding your first position',
    addFirstPosition: 'Add First Position',
    coin: 'Coin',
    selectCoin: 'Select Coin',
    positionType: 'Position Type',
    long: 'Long',
    short: 'Short',
    amount: 'Amount',
    entryPrice: 'Entry Price',
    currentPrice: 'Current Price',
    notes: 'Notes (Optional)',
    notesPlaceholder: 'Write your notes here...',
    cancel: 'Cancel',
    add: 'Add',
    update: 'Update',
    delete: 'Delete',
    edit: 'Edit',
    totalPortfolioValue: 'Total Portfolio Value',
    totalProfitLoss: 'Total Profit/Loss',
    totalPositions: 'Total Positions',
    currentValue: 'Current Value',
    profitLoss: 'Profit/Loss',
    profitLossPercent: 'Profit/Loss %',
    isLeveraged: 'Leveraged Trade?',
    yes: 'Yes',
    no: 'No',
    leverage: 'Leverage',
    longDescription: 'Profit from rise',
    shortDescription: 'Profit from fall',
    investmentAmount: 'Investment Amount',
    coinAmount: 'Coin Amount to Buy',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit (Target Price)',
    takeProfitShort: 'Target',
    stopLossShort: 'Stop',
    optional: 'Optional',
    stopLossPlaceholder: 'Stop loss price (optional)',
    takeProfitPlaceholder: 'Target price (optional)',
    stopLossResult: 'Stop Loss Result',
    takeProfitResult: 'Take Profit Result',
    stopLossTriggered: 'Stop Loss Triggered!',
    takeProfitTriggered: 'Take Profit Reached!',
    portfolioLoading: 'Loading portfolio...',
    searchCoin: 'Search coin...',
    noCoinFound: 'No coin found',
    spotTradeInfo: 'Spot trade: You profit from price increase.',
    spot: 'Spot',
    portfolioLoadError: 'Failed to load portfolio',
    positionAddError: 'Failed to add position',
    positionUpdateError: 'Failed to update position',
    positionDeleteError: 'Failed to delete position',
    // Trending
    trendingTitle: 'Trending Cryptocurrencies',
    trendingDescription: 'Discover the most popular coins with AI-powered trend analysis',
    trendScore: 'Trend Score',
    noTrendingCoins: 'No trending coins found',
    searchCryptos: 'Search cryptos...',
    noResultsFor: 'No results found for {searchTerm}',
    updating: 'Updating...',
    veryStrongTrend: 'Very Strong Trend',
    strongTrend: 'Strong Trend',
    moderateTrend: 'Moderate Trend',
    weakTrend: 'Weak Trend',
    veryWeakTrend: 'Very Weak Trend',
    strongBullish: 'Strong Bullish',
    bullish: 'Bullish',
    strongBearish: 'Strong Bearish',
    bearish: 'Bearish',
    positionBadgeLong: 'Long Position',
    positionBadgeShort: 'Short Position',
    positionBadgeNeutral: 'Neutral Position',
    trendScoreDescription: '📊 Measures a coin\'s popularity and activity in the market.\n\n• Price change\n• Trading volume\n• Liquidity\n• Market cap\n• Volatility\n\nScore: 0-100\n🟢 70-100: Strong trend\n🟡 30-70: Medium trend\n🔴 0-30: Weak trend',
    positionDescription: '🤖 AI model\'s recommended trading direction:\n\n📈 Long Position:\nPrice expected to rise → Buy\n\n📉 Short Position:\nPrice expected to fall → Sell\n\n⚪ Neutral:\nUncertainty\n\n⚠️ Not investment advice.',
    viewDetails: 'View Details',
    predictionBasePrice: 'Prediction Base Price',
    estimatedPrice: 'Estimated Price',
    estimatedChange: 'Estimated Change',
    direction: 'Direction',
    algorithmicPricePrediction: 'Algorithmic Price Prediction',
    totalTrendScore: 'Total Trend Score',
    totalTrendScoreDesc: 'Combined evaluation of all factors',
    detailedAnalysisMetrics: 'Detailed Analysis Metrics',
    liquidityScore: 'Liquidity Score',
    priceMomentum: 'Price Momentum',
    marketPosition: 'Market Position',
    volumeTrend: 'Volume Trend',
    volatilityScore: 'Volatility Score',
    volumeMarketCapRatio: 'Volume / Market Cap Ratio',
    priceChange24h: '24 Hour Price Change',
    marketCapRankDesc: 'Market Cap Ranking',
    tradingVolumeActivity: 'Trading Volume Activity',
    priceVolatility: 'Price Volatility',
    chartLoading: 'Loading chart...',
    priceAndChangeMobile: 'Price / 24h',
    marketCapMobile: 'Market Cap',
    supplyMobile: 'Supply',
    volumeMobile: 'Volume (24h)',
    noData: 'No data',
    volumeMarketCapExplanation: 'Volume and Market Cap Explanation',
    thousand: 'Thousand (K)',
    thousandExplanation: '1,000',
    million: 'Million (M)',
    millionExplanation: '1,000,000',
    billion: 'Billion (B)',
    billionExplanation: '1,000,000,000',
    trillion: 'Trillion (T)',
    trillionExplanation: '1,000,000,000,000',
    // Premium Route
    premiumRequired: 'Premium Membership Required',
    premiumRequiredDesc: 'You need a Premium membership to access this feature',
    premiumFeaturePortfolio: 'Portfolio Management',
    premiumFeaturePortfolioDesc: 'Long/Short position tracking, profit/loss calculation and price alerts',
    premiumFeatureDominance: 'Dominance Analysis',
    premiumFeatureDominanceDesc: 'BTC and ETH market dominance charts and trend analysis',
    premiumFeatureTrend: 'Trend Analysis',
    premiumFeatureTrendDesc: 'Track popular crypto trends and momentum scores',
    premiumFeatureFavorites: 'Favorites',
    premiumFeatureFavoritesDesc: 'Save your frequently used coins and access them quickly',
    premiumFeatureFedRate: 'Interest Rate Tracking',
    premiumFeatureFedRateDesc: 'Track FED interest rates and analyze market impacts',
    premiumFeatureSupply: 'Supply Tracking',
    premiumFeatureSupplyDesc: 'View coin supply changes in 24 hour, 7 day and 30 day periods',
    // Supply Tracking
    supplySearchPlaceholder: 'Search coins...',
    supplySortLabel: 'Sort',
    supplySortDefault: 'Default',
    supplySortName: 'Name',
    supplySortChange24h: '24h Change',
    supplySortChange7d: '7d Change',
    supplySortChange1m: '1m Change',
    supplyChange24h: '24h Change',
    supplyChange7d: '7d Change',
    supplyChange30d: '30d Change',
    circulatingSupplyFull: 'Circulating Supply',
    totalSupplyFull: 'Total Supply',
    maxSupplyFull: 'Max Supply',
    noSupplyData: 'No supply data yet',
    premiumFeatureMarket: 'Market Overview',
    premiumFeatureMarketDesc: 'Market overview, dominance charts and Fear & Greed Index',
    premiumFeatureCharts: 'Advanced Charts',
    premiumFeatureChartsDesc: 'Detailed OHLC candlestick charts and technical analysis tools',
    buyPremium: 'Buy Premium',
    backToHome: 'Back to Home',
    premiumContactInfo: 'For information about Premium membership:',
    telegram: 'Telegram',
    // NotFound Page
    notFoundBadge: 'Lost route',
    notFoundTitle: 'You jumped to the wrong coordinates',
    notFoundDescription: 'Radars could not find a portal at this point. Our star map is preparing to redirect you back to the main base. Meanwhile, gather your cosmic cloak and return to the safe route.',
    notFoundStatus1: 'Navigation recalculating',
    notFoundStatus2: 'Warp engine ready on standby',
    notFoundStatus3: 'Backup route being drawn',
    notFoundBackHome: 'Return to base',
    notFoundSupport: 'For ongoing issues, you can contact',
    notFoundSupportTeam: 'our support team',
    notFoundSupportContact: '.',
    // Dominance Page
    dominanceTitle: 'Market Dominance',
    dominanceDescription: 'Bitcoin and Ethereum market dominance analysis',
    dominanceTable: 'Dominance Table',
    topDominance: 'Dominance',
    totalBtcVolume: 'Total BTC Volume',
    // Admin Management
    adminManagement: 'User Management',
    adminManagementDescription: 'View, edit and manage users',
    unauthorizedAccess: 'Unauthorized Access',
    unauthorizedAccessDesc: 'You need admin privileges to access this page.',
    searchUser: 'Search user...',
    all: 'All',
    regular: 'Regular',
    inactive: 'Inactive',
    totalUsers: 'Total Users',
    premiumUsers: 'Premium Users',
    regularUsers: 'Regular Users',
    refresh: 'Refresh',
    makePremium: 'Make Premium',
    removePremium: 'Remove Premium',
    makeAdmin: 'Make Admin',
    removeAdmin: 'Remove Admin',
    activate: 'Activate',
    deactivate: 'Deactivate',
    userNotFoundDescription: 'No user found matching your search criteria.',
    unknown: 'Unknown',
    userId: 'User ID',
    marketCapPercentage: 'Market Cap Percentage',
    volume24hDominance: '24h Volume Dominance',
    change24hDominance: '24h Change',
    cryptocurrency: 'Cryptocurrency',
    marketShareDistributionOverlay: 'Market Share Distribution',
    last7Days: 'Last 7 Days',
    volumeAnalysis: 'Volume Analysis',
    dataLoading: 'Loading data...',
    date: 'Date',
    dominance: 'Dominance',
    extremeFear: 'Extreme Fear',
    fear: 'Fear',
    neutral: 'Neutral',
    greed: 'Greed',
    extremeGreed: 'Extreme Greed',
    dominanceApiErrorTitle: 'Failed to Load Data',
    dominanceApiErrorDesc: 'An error occurred while loading dominance data. Please try again later.',
    others: 'Others',
    // Settings Page
    settingsTitle: 'Settings',
    settingsDescription: 'Manage your profile, display settings, and security.',
    profileInfo: 'Profile Information',
    display: 'Display',
    theme: 'Theme',
    themeDescription: 'Select the interface theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    languageLabel: 'Language',
    currency: 'Currency',
    currencyLabel: 'Currency',
    usd: 'USD',
    eur: 'EUR',
    try: 'TRY',
    currentRates: 'Rates in TRY',
    passwordChange: 'Password Change',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    enterCurrentPassword: 'Enter your current password',
    enterNewPassword: 'Enter your new password',
    changePassword: 'Change Password',
    setPassword: 'Set Password',
    changingPassword: 'Changing password...',
    passwordStrength: 'Password Strength',
    minLength: '8+ Characters',
    hasUppercase: 'At least one uppercase letter',
    hasLowercase: 'At least one lowercase letter',
    hasNumber: 'At least one number',
    hasSpecialChar: 'At least one special character',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    veryStrong: 'Very Strong',
    passwordTooWeak: 'Password too weak',
    currentPasswordRequired: 'Current password required',
    newPasswordRequired: 'New password required',
    wrongCurrentPassword: 'Current password is incorrect',
    passwordChanged: 'Password changed successfully',
    newPasswordMustBeDifferent: 'New password cannot be the same as the current password',
    accountDeletion: 'Account Deletion',
    deleteAccountPermanently: 'Permanently delete your account and all your data.',
    deleteMyAccount: 'Delete My Account',
    confirmAccountDeletion: 'Confirm Account Deletion',
    accountDeletionWarning: 'This action cannot be undone. Your account and all associated data will be permanently deleted.',
    dataToBeDeleted: 'Data to be Deleted:',
    personalInformation: 'Personal Information',
    favoriteCryptoList: 'Your Favorite Crypto List',
    accountSettings: 'Your Account Settings',
    allCacheData: 'All Cache Data',
    accountDeletionPasswordNote: 'You must enter your current password to delete your account.',
    yesDeleteAccount: 'Yes, Delete My Account',
    accountDeletedSuccessfully: 'Account deleted successfully',
    accountDeletionError: 'Account deletion error',
    deleting: 'Deleting',
    confirm: 'Confirm',
    save: 'Save',
    saving: 'Saving...',
    saveSuccess: 'Saved successfully',
    saveError: 'Save error',
    loginRequiredToSave: 'Login required to save',
    loginRequiredToReset: 'Login required to reset',
    resetSettings: 'Reset Settings',
    settingsReset: 'Settings reset',
    unsavedChanges: 'There are unsaved changes',
    updateProfile: 'Update Profile',
    updatingProfile: 'Updating profile...',
    profileUpdateSuccess: 'Profile updated successfully',
    profileUpdateError: 'Profile update error',
    loading: 'Loading...',
    settingsSummary: 'Settings Summary',
    // MiniChart
    chartClickToView: 'Click on the coin card to view the chart',
    chartDataLoading: 'Loading data...',
    chartDataUnavailable: 'OHLC data unavailable',
    chartDataLoadError: 'Failed to load OHLC data',
    // Dominance
    marketDominanceBreakdown: 'Market dominance breakdown',
    topCryptocurrenciesByVolume: 'Top cryptocurrencies by volume',
    // Layout
    loadingPage: 'Loading...',
    // Common
    notAvailable: 'Not Available',
    loadUsersError: 'Failed to load users',
    togglePremiumError: 'Failed to change premium status',
    toggleActiveError: 'Failed to change user status',
    toggleAdminError: 'Failed to change admin status',
    bitcoin: 'Bitcoin',
    ethereum: 'Ethereum',
    // News
    cryptoNews: 'Crypto News',
    justNow: 'just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    searchNews: 'Search news...',
    errorLoadingNews: 'An error occurred while loading news:',
    noNewsFound: 'No news found matching your criteria',
    noNews: 'No news yet',
    readMore: 'Read More',
    important: 'Important',
    positive: 'Positive',
    negative: 'Negative',
    highPriorityNews: 'High Priority News',
    criticalImportance: 'News of critical importance',
    recordOrImportant: 'Record or important developments',
    positiveNews: 'Positive News',
    negativeNews: 'Negative News',
    neutralNews: 'Neutral News',
    positiveNewsDesc: 'Positive news for the market',
    negativeNewsDesc: 'Negative news for the market',
    neutralNewsDesc: 'Informational news',
    positiveForMarket: 'Positive for market',
    needsCaution: 'Requires caution',
    informationalOnly: 'Informational only',
    marketImpactAnalysis: 'Market Impact Analysis',
    negativeForMarket: 'Negative for market',
    aiAnalysisNeutral: 'Informational',
    newsCategory: 'News Category',
    category: 'Category',
    categoryBitcoin: 'Bitcoin',
    categoryEthereum: 'Ethereum',
    categoryDefi: 'DeFi',
    categoryNft: 'NFT',
    categoryRegulation: 'Regulation',
    categoryExchange: 'Exchange',
    categoryMarket: 'Market',
    categoryAltcoin: 'Altcoin',
    categoryBitcoinShort: 'Bitcoin news',
    categoryEthereumShort: 'Ethereum news',
    categoryDefiShort: 'DeFi news',
    categoryNftShort: 'NFT news',
    categoryRegulationShort: 'Regulation news',
    categoryExchangeShort: 'Exchange news',
    categoryMarketShort: 'Market news',
    categoryAltcoinShort: 'Altcoin news',
    defi: 'DeFi',
    nft: 'NFT',
    regulation: 'Regulation',
    exchange: 'Exchange',
    market: 'Market',
    altcoin: 'Altcoin',
    // Fed Rate
    fedRateDescription: 'Track FED interest rates and analyze market impacts',
    fedRateDecision: 'Fed Rate Decision',
    announced: 'Announced',
    previous: 'Previous',
    lastPublished: 'Last Published',
    nextDecision: 'Next Decision',
    fedRssLink: 'Fed RSS Link',
    fomcCalendarLink: 'FOMC Calendar',
    announcing: 'Announcing...',
    waitingForData: 'Waiting for data...',
    week: 'Week',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    second: 'Second',
    fredApiKeyMissing: 'FRED API key is missing',
    fedRateDataError: 'Fed Rate data could not be loaded. Please refresh the page.'
  }
}

export const LanguageProvider = ({ children }) => {
  // localStorage'dan dil yükle - ANINDA (F5 sonrası hemen uygula)
  const getInitialLanguage = () => {
    if (typeof window === 'undefined') return 'tr'
    const saved = localStorage.getItem('language')
    return saved || 'tr'
  }

  const [language, setLanguage] = useState(getInitialLanguage)

  // Dil değişikliklerini localStorage'a kaydet - ANINDA
  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  // MongoDB'den gelen language değişikliklerini dinle
  useEffect(() => {
    const handleLanguageChange = (event) => {
      const newLanguage = event.detail
      setLanguage(newLanguage)
      localStorage.setItem('language', newLanguage) // localStorage'a da kaydet
    }
    
    window.addEventListener('languageChanged', handleLanguageChange)
    return () => window.removeEventListener('languageChanged', handleLanguageChange)
  }, [])

  const changeLanguage = (lang) => {
    setLanguage(lang)
    localStorage.setItem('language', lang) // Anında localStorage'a kaydet
  }

  const t = (key, params = {}) => {
    const dict = translations[language] || translations.tr
    let translation = dict[key] || key
    // Replace params like {attempts} with actual values
    Object.keys(params).forEach(paramKey => {
      translation = translation.replace(`{${paramKey}}`, params[paramKey])
    })
    return translation
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export { useLanguage }


